### ISSUE TITLE
x and y coordinates are swapped

### ISSUE THREAD

**Issue by ktugan** [BioroboticsLab/bb_binary#20]
The x and y coordinates are currently swapped. This leads to a lot of weird code where we always have to correct this mistake.

I would propose to fix this mistake, I previously assumed that this was intended. Recent developement revealed that this is not so.

Examples of weird code:

1. `ax.quiver(y, x, ...)]` simple
2. Vector which represents zero angle is now 0/10 instead 10/0
```
def rotate_direction_vec(rotation):
    x, y = 0, 10
    sined = np.sin(rotation)
    cosined = np.cos(rotation)
    normed_x = x*cosined - y*sined
    normed_y = x*sined + y*cosined
    return [np.around(normed_x, decimals=2), np.around(normed_y, decimals=2)]
```

**Comment by ktugan** [comment]
how to:

```
# copies in a static manner the values of a framecontainer into a new one
def deepcopy_framecontainer(fc, fc2):
    fc2.camId = fc.camId
    
    fc2.init('dataSources', len(fc.dataSources))
    for i, datasource in enumerate(fc.dataSources):
        fc2.dataSources[i] = fc.dataSources[i]
    fc2.fromTimestamp = fc.fromTimestamp
    fc2.hiveId = fc.hiveId
    fc2.id = fc.id
    fc2.toTimestamp = fc.toTimestamp
    
    fc2.init('transformationMatrix', len(fc.transformationMatrix))
    for i, tm in enumerate(fc.transformationMatrix):
        fc2.transformationMatrix[i] = fc.transformationMatrix[i]
    
    fc2.init('frames', len(fc.frames))
    for i, frame in enumerate(fc.frames):
        fc2.frames[i] = fc.frames[i]


from bb_binary import Repository, FrameContainer

repo = Repository('data/1h_09-25-15/')
repo_fixed = Repository('data/1h_09-25-15_fixed2/')

for fname in repo.iter_fnames():
    fc = load_frame_container(fname)
    fc2 = FrameContainer.new_message()
    deepcopy_framecontainer(fc, fc2)
    
    for frame in fc2.frames:
    	for detection in frame.detectionsUnion.detectionsDP:
    		detection.x, detection.y = detection.y, detection.x
    
    repo_fixed.add(fc2)

```

**Comment by gitmirgut** [comment]
If **all** `DetectionDP.xpos` and `DetectionDP.ypos` in the **whole** repro are swapped, i think it is faster to just change the [bb_binary_schema.capnp](https://github.com/BioroboticsLab/bb_binary/blob/master/bb_binary/bb_binary_schema.capnp).
**From:**
``` capnp
struct DetectionDP {
...
  xpos @1 :UInt16;               # x coordinate of the grid center wrt. the image
  ypos @2 :UInt16;               # y coordinate of the grid center wrt. the image
...
}
```
**To:**
``` capnp
struct DetectionDP {
...
  ypos @1 :UInt16;               # x coordinate of the grid center wrt. the image
  xpos @2 :UInt16;               # y coordinate of the grid center wrt. the image
...
}
```
But then we have to fix the  output of *DP* simultaneous, otherwise we produce multiple inconsistent data, where `xpos` and `ypos` are sometimes swapped and sometimes not.

If I am not mistaken, the swap of the coordinates in the *DP* was happening in [bb_pipeline-processing.py](https://github.com/BioroboticsLab/bb_pipeline/blob/master/pipeline/stages/processing.py#L107) at line `L107`. 
```python
positions = peak_local_max(im, min_distance=dist)
```
[peak_local_max](http://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.peak_local_max) returns the row (y-Axis) first and then the column(x-Axis).

**Comment by nebw** [comment]
See also https://github.com/BioroboticsLab/bb_pipeline/commit/c8f894250646a6d2886ceac99f905567a20ec8f5

Thanks for the suggestion @gitmirgut
